# Generated by Django 4.2.6 on 2024-05-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
