# Generated by Django 4.2.6 on 2024-05-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_remove_owner_capacity_owner_address_owner_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='address',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='email',
        ),
        migrations.AddField(
            model_name='owner',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='state',
            field=models.CharField(default='', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='street',
            field=models.CharField(default='', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='zipcode',
            field=models.CharField(default='', max_length=400, null=True),
        ),
    ]
