# Generated by Django 4.2.6 on 2024-05-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_rename_address_owner_city_remove_owner_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recycleform',
            name='time',
        ),
        migrations.AddField(
            model_name='recycleform',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='recycleform',
            name='organisation_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recycleform',
            name='organisation_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='organisation_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
