# Generated by Django 4.2.6 on 2024-05-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_remove_recycleform_time_recycleform_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recycleform',
            name='organisation_id',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='recycleform',
            name='organisation_name',
            field=models.CharField(default='Empty', max_length=100),
        ),
    ]
