# Generated by Django 4.2.6 on 2024-05-23 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0017_alter_recycleform_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='organisation_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recycleform',
            name='organisation_id',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
