# Generated by Django 4.2.6 on 2024-05-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_alter_owner_organisation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='organisation_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
