# Generated by Django 4.2.6 on 2024-05-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_alter_owner_organisation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='id',
        ),
        migrations.AlterField(
            model_name='owner',
            name='organisation_id',
            field=models.IntegerField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
    ]
