# Generated by Django 4.2.6 on 2024-05-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0024_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
