# Generated by Django 5.0.4 on 2024-05-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0028_alter_recycleform_options_recycleform_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycleform',
            name='status',
            field=models.CharField(default=False, max_length=10, null=True),
        ),
    ]
