# Generated by Django 5.0.4 on 2024-10-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0032_rename_name_recycleform_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycleform',
            name='user_id',
            field=models.CharField(default=1, max_length=100, null=True),
        ),
    ]
