# Generated by Django 5.2.1 on 2025-06-27 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_notification_seen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='organisation_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='owner',
            name='organisation_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='owner',
            name='state',
            field=models.CharField(blank=True, db_index=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='zipcode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recycleform',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='recycleform',
            name='date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='recycleform',
            name='item_type',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recycleform',
            name='status',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['city', 'state'], name='myApp_owner_city_335efc_idx'),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['user'], name='myApp_owner_user_id_41f9c5_idx'),
        ),
        migrations.AddIndex(
            model_name='recycleform',
            index=models.Index(fields=['user', 'status'], name='myApp_recyc_user_id_3e99e1_idx'),
        ),
        migrations.AddIndex(
            model_name='recycleform',
            index=models.Index(fields=['item_type', 'created'], name='myApp_recyc_item_ty_768782_idx'),
        ),
    ]
